# app/config/routing.yml
default_show:
    path: /default/show
    defaults: { _controller: AppBundle:Default:show }
default_create:
    path: /default/create
    defaults: { _controller: AppBundle:Default:create }
default_delete:
    path: /default/delete/{productId}
    defaults: { _controller: AppBundle:Default:delete }
default_update:
    path: /default/update/{productId}
    defaults: { _controller: AppBundle:Default:update }
app:
    resource: '@AppBundle/Controller/'
    type: annotation