<?php

namespace AppBundle\Repository;

/**
 * lsxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lsxRepository extends \Doctrine\ORM\EntityRepository
{
}
